namespace MockForge.StaticData;

public static class HousingDataStore
{
    public static readonly string[] ApartmentCShortPhrases =
    [
        "no ventilation",
        "no natural light",
        "underground",
        "small footprint",
        "low ceiling",
        "damp-prone",
        "artificial lighting only",
        "minimal amenities",
        "basement location",
        "restricted egress",
        "compact layout",
        "basic utilities",
        "windowless",
        "cold walls",
        "poor insulation",
        "limited headroom",
        "low privacy",
        "shared corridor",
        "no balcony",
        "single-room",
        "concrete walls",
        "stuffy",
        "mold risk",
        "limited storage",
        "narrow stair access",
        "noisy mechanical systems",
        "low resale value",
        "economy-grade fixtures",
        "minimal ventilation openings",
        "short-term rental likely"
    ];

    public static readonly string[] ApartmentBShortPhrases =
    [
        "limited windows",
        "poor daylight",
        "restricted airflow",
        "small rooms",
        "economy finishes",
        "compact kitchen",
        "low natural light",
        "modest storage",
        "city-facing",
        "tight layout",
        "practical for single occupancy",
        "budget-friendly",
        "standard fixtures",
        "short-term rental friendly",
        "minimal insulation",
        "low ceiling height",
        "internal bathroom",
        "no balcony",
        "shared entrance",
        "close to amenities",
        "compact bedroom",
        "limited wardrobe space",
        "modest view",
        "basic heating",
        "affordable",
        "efficient layout",
        "low maintenance",
        "good for commuters",
        "near public transport",
        "city-center convenience"
    ];

    public static readonly string[] ApartmentAShortPhrases =
    [
        "medium size",
        "moderate light",
        "some scenic views",
        "decent ventilation",
        "functional layout",
        "neighborhood-facing",
        "occasional balcony",
        "comfortable living area",
        "good daylight in main rooms",
        "balanced proportions",
        "well-suited for families",
        "practical storage",
        "open-plan living",
        "separate kitchen",
        "natural airflow",
        "multiple windows",
        "pleasant outlook",
        "parking available",
        "near parks",
        "modern finishes",
        "ample daylight",
        "versatile rooms",
        "starter-family friendly",
        "safe location",
        "well-connected transport",
        "elevator access",
        "functional balcony",
        "solid insulation",
        "flexible layout",
        "community amenities"
    ];

    public static readonly string[] ApartmentLShortPhrases =
    [
        "large and spacious",
        "many windows",
        "abundant natural light",
        "excellent ventilation",
        "premium finishes",
        "multiple en-suite bathrooms",
        "private parking",
        "generous storage",
        "formal dining area",
        "entertaining spaces",
        "high ceilings",
        "grand entrance",
        "designer kitchen",
        "marble surfaces",
        "private lift",
        "valet parking",
        "floor-to-ceiling glazing",
        "private terrace",
        "landscaped garden",
        "spa bathroom",
        "walk-in closets",
        "security system",
        "smart home features",
        "wine cellar potential",
        "home office",
        "heated floors",
        "impressive foyer",
        "premium appliances",
        "concierge service",
        "ample natural ventilation"
    ];

    public static readonly string[] ApartmentATShortPhrases =
    [
        "penthouse terrace",
        "private rooftop garden",
        "panoramic views",
        "single unit per landing",
        "private elevator",
        "dedicated parking",
        "large outdoor terraces",
        "luxury amenities",
        "mansions-style rooms",
        "exclusive location",
        "roof deck",
        "private access",
        "rooftop pool",
        "private sauna",
        "outdoor kitchen",
        "garden planters",
        "staff quarters",
        "private garage",
        "formal entrance",
        "private sky-lounge",
        "stunning skyline views",
        "architect-designed",
        "high-end landscaping",
        "bespoke interiors",
        "art gallery space",
        "separate guest wing",
        "climate-controlled storage",
        "private cinema",
        "prestige address",
        "roof terrace dining"
    ];
}
