namespace MockForge.StaticData;

public static class IdentityDataStore
{
    public static readonly string[] GenderData =
    [
        "Male",
        "Female",
        "NonBinary",
        "NonGender",
        "Fluid",
        "Hermaphrodite",
        "Agender",
        "Bigender",
        "Demigender",
        "Androgyne",
    ];

    public static readonly string[] LastNameData =
    [
        "Smith",
        "Johnson",
        "Williams",
        "Brown",
        "Jones",
        "Garcia",
        "Miller",
        "Davis",
        "Rodriguez",
        "Martinez",
        "Hernandez",
        "Lopez",
        "Gonzalez",
        "Wilson",
        "Anderson"
    ];

    public static readonly string[] MaleNameData =
    [
        "Alexandre",
        "Giovanni",
        "Oliver",
        "Hans",
        "Miguel",
        "Lucas",
        "Émile",
        "Lars",
        "Seán",
        "Matthias",
        "Aleksandr",
        "Piotr",
        "Istvan",
        "Dimitar",
        "Ion",
        "Nikita",
        "Marek",
        "Arunas",
        "Kristaps",
        "Vlado",
        "Michael",
        "James",
        "Jose",
        "William",
        "Liam",
        "Juan",
        "Robert",
        "Ethan",
        "Alejandro",
        "David",
        "Matías",
        "Sebastian",
        "Andres",
        "Rodrigo",
        "Carlos",
        "Daniel",
        "Gabriel",
        "Esteban",
        "Jorge",
        "Mohammad",
        "Ahmed",
        "Ali",
        "Yusuf",
        "Mostafa",
        "Omar",
        "Hassan",
        "Khalid",
        "Ibrahim",
        "Nabil",
        "Kwame",
        "Thabo",
        "Chinedu",
        "Abebe",
        "Juma",
        "Oluwaseun",
        "Kofi",
        "Amadou",
        "Zola",
        "Youssef",
        "Mahdi",
        "Anwar",
        "Karim",
        "Said",
        "Hamid",
        "Samir",
        "Nadir",
        "Rachid",
        "Rahul",
        "Muhammad",
        "Sanjay",
        "Ramesh",
        "Shafiq",
        "Amir",
        "Pradeep",
        "Arun",
        "Sajid",
        "Wei",
        "Takumi",
        "Nguyen",
        "Achmad",
        "Satoshi",
        "Chen",
        "Jiro",
        "An",
        "Than",
        "Jack",
        "Kaha",
        "Tui",
        "Mani",
        "Tevita",
        "George",
        "Patrick",
        "Jone",
        "Eroni"
    ];

    public static readonly string[] FemaleNameData =
    [
        "Marie",
        "Chiara",
        "Olivia",
        "Anna",
        "Sofia",
        "Inis",
        "Elise",
        "Maud",
        "Aoife",
        "Lea",
        "Anastasia",
        "Zofia",
        "Eszter",
        "Ekaterina",
        "Mihaela",
        "Kateryna",
        "Katarena",
        "Egle",
        "Elina",
        "Milica",
        "Emily",
        "Charlotte",
        "Ximena",
        "Harper",
        "Sophia",
        "Mia",
        "Ava",
        "Zoe",
        "Isabella",
        "Lily",
        "Valentina",
        "Camila",
        "Fernanda",
        "Carolina",
        "Ana",
        "Natalia",
        "Laura",
        "Maria",
        "Patricia",
        "Gabriela",
        "Fatima",
        "Sara",
        "Zahra",
        "Elif",
        "Maya",
        "Noor",
        "Aisha",
        "Lina",
        "Dima",
        "Nouf",
        "Ama",
        "Thandi",
        "Amina",
        "Chioma",
        "Lulit",
        "Zuri",
        "Adjoa",
        "Nomvula",
        "Nia",
        "Zawadi",
        "Asma",
        "Samira",
        "Leila",
        "Khadija",
        "Salma",
        "Mona",
        "Nadia",
        "Rachida",
        "Yusra",
        "Amel",
        "Priya",
        "Nida",
        "Sita",
        "Rahima",
        "Anjali",
        "Deepika",
        "Kavya",
        "Nirmala",
        "Chamari",
        "Shanti",
        "Li",
        "Sakura",
        "Jiwoo",
        "Thúy",
        "Ayu",
        "Haruka",
        "Mei",
        "Yuna",
        "Linh",
        "Putri",
        "Pania",
        "Aroha",
        "Fia",
        "Mele",
        "Anahera",
        "Marama",
        "Litia",
        "Ema",
        "Fetu",
        "Malia"
    ];

    public static readonly string[] FemaleNobleTitleData =
    [
        "Duchess",
        "Countess",
        "Baroness",
        "Lady",
        "Dame"
    ];

    public static readonly string[] MaleNobleTitleData =
    [
        "Duke",
        "Count",
        "Baron",
        "Lord",
        "Sir",
    ];

    public static readonly string[] FemaleTitleData =
    [
        "Mrs",
        "Miss",
        "Ms",
        "Dr",
        "Prof",
    ];

    public static readonly string[] MaleTitleData =
    [
        "Mr",
        "Dr",
        "Prof",
    ];

    public static readonly string[] CityData =
    [
        "London",
        "Paris",
        "Berlin",
        "Madrid",
        "Rome",
        "Amsterdam",
        "Vienna",
        "Lisbon",
        "Dublin",
        "Stockholm",
        "Tokyo",
        "Shanghai",
        "Beijing",
        "Mumbai",
        "Delhi",
        "Seoul",
        "Bangkok",
        "Singapore",
        "Hong Kong",
        "Jakarta",
        "Cairo",
        "Lagos",
        "Johannesburg",
        "Nairobi",
        "Casablanca",
        "Accra",
        "Addis Ababa",
        "Tunis",
        "Algiers",
        "Dakar",
        "New York",
        "Los Angeles",
        "Chicago",
        "Toronto",
        "Mexico City",
        "Houston",
        "Montreal",
        "Miami",
        "Vancouver",
        "San Francisco",
        "São Paulo",
        "Buenos Aires",
        "Rio de Janeiro",
        "Bogotá",
        "Lima",
        "Santiago",
        "Caracas",
        "Quito",
        "Montevideo",
        "Salvador",
        "Sydney",
        "Melbourne",
        "Auckland",
        "Brisbane",
        "Perth",
        "Wellington",
        "Suva",
        "Port Moresby",
        "Honolulu",
        "Christchurch",
        "Dubai",
        "Istanbul",
        "Riyadh",
        "Tel Aviv",
        "Doha",
        "Kuwait City",
        "Beirut",
        "Tehran",
        "Amman",
        "Muscat",
        "Moscow",
        "Astana",
        "Tashkent",
        "Almaty",
        "Bishkek",
        "Dushanbe",
        "Ashgabat",
        "Yerevan",
        "Baku",
        "Tbilisi",
        "Barcelona",
        "Frankfurt",
        "Munich",
        "Warsaw",
        "Budapest",
        "Prague",
        "Copenhagen",
        "Helsinki",
        "Oslo",
        "Zurich",
        "Seattle",
        "Boston",
        "Atlanta",
        "Dallas",
        "Philadelphia",
        "Phoenix",
        "Manchester",
        "Lyon",
        "Rotterdam",
        "Hamburg",
    ];

    public static readonly string[] DepartmentData =
    [
        "Human Resources",
        "Finance",
        "Marketing",
        "Sales",
        "Research & Development",
        "Information Technology",
        "Operations",
        "Legal",
        "Logistics",
        "Customer Service",
        "Quality Control",
        "Corporate Communications",
        "Strategy & Planning",
        "Corporate Social Responsibility",
        "Occupational Health & Safety",
        "Internal Audit",
        "Public Relations",
        "Project Management",
    ];

    public static readonly string[] CompanyData =
    [
        "AstraNova Holdings",
        "Blue Horizon Energy",
        "QuantumLeap Solutions",
        "Infinite Group",
        "Terranova Biotech",
        "NexaCorp Global",
        "Solstice Innovations",
        "Altura Financial Services",
        "LumenTech Systems",
        "EcoVita Resources",
        "Vortex Dynamics",
        "Celeste Robotics",
        "Orbis Marketing",
        "FusionWave Media",
        "Axis Builders",
        "Sentinel Security",
        "Vertex Consultants",
        "Aurora Pharma",
        "Pangea Shipping",
        "NovaPlex Networks",
        "TerraPrime Market",
        "OptiMax Logistics",
        "Zenith Apparel",
        "BluePeak Ventures",
        "QuantumGrid Energy",
        "Prism Architecture",
        "Omnia Health",
        "Sigma Aerospace",
        "MetroLink Transit",
        "Elevate Real Estate",
        "CypherTech Cybersecurity",
        "BioHorizon Labs",
        "SkyBridge Airlines",
        "EcoSphere Agriculture",
        "Lumina Entertainment",
        "AlphaWave Artificial Intelligence",
        "GlobalVista Analytics",
        "Nexus Education",
        "TransWorld Freight",
        "Solara Resort Management",
        "Titan Manufacturing",
        "VitalCore Nutrition",
        "Emerald Financial Group",
        "NeoFusion Engineering",
        "EcoSense Urban Planning",
        "Helix Digital",
        "Meridian Travel",
        "UrbanPulse Real Estate",
        "Hyperion Automotive",
        "AcquaPure Systems"
    ];
}
